[package]
name = "rust_swift"
version = "0.1.0"
edition = "2024"

build = "build.rs"

[dependencies]
swift-bridge = "0.1"

[build-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
swift-bridge-build = "0.1"